# Generated by Django 4.2.6 on 2023-12-07 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_name',
        ),
    ]
