# Generated by Django 4.2.6 on 2023-12-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0002_remove_class_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_name',
            field=models.CharField(default='One', max_length=64),
        ),
    ]
