# Generated by Django 4.2.6 on 2023-12-09 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0004_alter_class_class_name_alter_class_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='D_O_B',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
