# Generated by Django 4.2.6 on 2023-12-13 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0005_alter_student_d_o_b'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('roll_no', 'std_name')},
        ),
    ]
