# Generated by Django 4.2.6 on 2023-12-07 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrative', '0002_remove_class_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('paid', models.IntegerField()),
                ('due', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassBills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_fee', models.IntegerField()),
                ('admissioin_fee', models.IntegerField()),
                ('T_C_certificate_fee', models.IntegerField()),
                ('indv_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrative.class')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualStudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportation', models.IntegerField(default=0)),
                ('class_wise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.classbills')),
            ],
        ),
    ]
