# Generated by Django 4.2.6 on 2023-12-08 03:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0004_alter_class_class_name_alter_class_section'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='id',
        ),
        migrations.AddField(
            model_name='billing',
            name='date_of_billing',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='billing',
            name='previous_due',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='recipt_no',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='student_name',
            field=models.ForeignKey(default=0 , on_delete=django.db.models.deletion.CASCADE, to='administrative.student'),
            preserve_default=False,
        ),
    ]
