# Generated by Django 4.2.6 on 2023-12-10 02:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0005_alter_student_d_o_b'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportRoutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=64)),
                ('transport_fee', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='billing',
            name='id',
        ),
        migrations.RemoveField(
            model_name='classbills',
            name='T_C_certificate_fee',
        ),
        migrations.AddField(
            model_name='billing',
            name='T_C_certificate_fee',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='date_of_billing',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='billing',
            name='others',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='previous_due',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='recipt_no',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billing',
            name='student',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='administrative.student'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='due',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='paid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='classbills',
            name='admissioin_fee',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='classbills',
            name='monthly_fee',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='IndividualStudentFee',
        ),
        migrations.AddField(
            model_name='billing',
            name='transportation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.transportroutes'),
        ),
    ]
