# Generated by Django 4.2.6 on 2023-12-12 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0005_alter_student_d_o_b'),
        ('billing', '0002_transportroutes_remove_billing_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='due',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='classbills',
            name='indv_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative.class'),
        ),
        migrations.CreateModel(
            name='PreviousDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.billing')),
                ('std', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administrative.student')),
            ],
        ),
        migrations.AlterField(
            model_name='billing',
            name='previous_due',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.previousdue'),
        ),
    ]
