# Generated by Django 4.2.6 on 2023-12-12 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_billing_due_alter_classbills_indv_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='due',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='previous_due',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='billing.billing'),
        ),
        migrations.DeleteModel(
            name='PreviousDue',
        ),
    ]
