# Generated by Django 4.2.6 on 2023-12-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_billing_due_alter_billing_previous_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='previous_due',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
