# Generated by Django 4.2.6 on 2023-12-13 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0005_alter_student_d_o_b'),
        ('billing', '0006_alter_billing_paid_alter_billing_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='billing',
            name='admission',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='monthly',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrative.student'),
        ),
        migrations.AddField(
            model_name='billing',
            name='months',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='billing.months'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='billing',
            unique_together={('student', 'months')},
        ),
    ]
