# Generated by Django 4.2.6 on 2023-12-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_months_billing_admission_billing_monthly_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billing',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='months',
            name='name',
            field=models.CharField(choices=[('Baisakh', 'Baisakh'), ('Jestha', 'Jestha'), ('Ashad', 'Ashad'), ('Shrawan', 'Shrawan'), ('Bhadra', 'Bhadra'), ('Ashoj', 'Ashoj'), ('Kartik', 'Kartik'), ('Mangsir', 'Mangsir'), ('Paush', 'Paush'), ('Magh', 'Magh'), ('Falgun', 'Falgun'), ('Chaitra', 'Chaitra')], max_length=64),
        ),
        migrations.RemoveField(
            model_name='billing',
            name='months',
        ),
        migrations.AddField(
            model_name='billing',
            name='months',
            field=models.ManyToManyField(to='billing.months'),
        ),
    ]
